### ISSUE TITLE
Configuring machdyne blaustahl storage device for direct data access via serial port

### ISSUE THREAD

**Issue by binqbit** [machdyne/blaustahl#9]
I have a question regarding the possibility of configuring the Machdyne Blaustahl Storage Device to enable direct data reading and writing through my custom software, without using a terminal interface. Could you please provide guidance or documentation on how to effectively integrate this functionality via the serial port, if this is possible?

**Comment by machdyne** [comment]
Hello. I plan to create a simple SDK/API for this but at the moment the best example I can offer is the [bs](https://github.com/machdyne/blaustahl/tree/main/sw) utility, which uses libusb to communicate with the composite firmware using a USB "vendor class" interface and allows reading/writing of the FRAM from the host computer.

Another possibility would be to add a mode to the firmware that  provides something like an AT command set for reading and writing data. That would also work on the CDC-only firmware.

If you'd like to provide any more details about what you're trying to accomplish I may be able to help with your specific case.

**Comment by binqbit** [comment]
Hi,
If anyone still has a similar question, I've found a simple solution and already implemented it. In my fork of the repository, all necessary changes have been made to the driver to support a simple read/write protocol, and the drivers are ready to use. Here are the links for those who need them:

1. Fork of the repository with updated drivers: [blaustahl](https://github.com/binqbit/blaustahl).
2. Example code of the application implementing the protocol: [serialport_srwp](https://github.com/binqbit/serialport_srwp).

**Comment by machdyne** [comment]
I think this is a great solution. Feel free to submit a PR if you'd like.
